// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hospitalinformationsystem.Models;

#nullable disable

namespace hospitalinformationsystem.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220617232607_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("hospitalinformationsystem.Models.PatientInfoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("InsertedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("birthType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("fatherBloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motherBloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("patientHeight")
                        .HasColumnType("real");

                    b.Property<string>("patientMotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientNo")
                        .HasColumnType("int");

                    b.Property<string>("patientSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("patientWeight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("patientInfoModels");
                });

            modelBuilder.Entity("hospitalinformationsystem.Models.StaffModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctorNo")
                        .HasColumnType("int");

                    b.Property<string>("doctorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("staffModels");
                });
#pragma warning restore 612, 618
        }
    }
}
